version: "3.7"
  # Runs a local redis version.
services:
  redis:
    # This version should match our Elasticache instances.
    image: 604255211065.dkr.ecr.us-east-2.amazonaws.com/base-redis:latest
    volumes:
      - /var/lib/redis/data
  channels:
    image: channels:dev-latest
    build:
      context: .
    volumes:
      - .:/app
