version: "3.7"
  # Runs a local redis version.
services:
  redis:
    # This version should match our Elasticache instances.
    image: redis:5.0.6
    volumes:
      - /var/lib/redis/data
  channels:
    image: channels:dev-latest
    build:
      context: .
    volumes:
      - .:/app
