version: "3.7"
  # Runs a local redis version.
services:
  redis:
    # This version should match our Elasticache instances.
    image: 604255211065.dkr.ecr.us-east-1.amazonaws.com/base-redis:latest
    volumes:
      - /var/lib/redis/data
  channels:
    image: channels:dev-latest
    build:
      context: .
    environment:
      # These particular environment variables must be provided from the
      # invoking shell to account for MFA.
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - .:/app
